=== Як перекладати

.Процес робити перекладу розділу:

. Перекладач створює гілку chXXX_1_translation (де XXX - номер розділу, наприклад, 22)
. Спершу продивляється оригінал на http://hpmor.com/chapter/XXX В наших файлах оригіналу відсутні:
.. Горизонатльні лініі (треба додати `\***` перед абзацем, над яким горизонтальна лінія)
.. Центрований текст (треба писати переклад так: `[center]\#ТЕКСТ#`)
.. Центрований підкреслений текст (треба писати переклад так: `{plus}{plus}{plus}<center>{plus}{plus}{plus}[underline]\#ТЕКСТ#{plus}{plus}{plus}</center>{plus}{plus}{plus}`)
.. У назву розділу треба додати "`Розділ XXX`" (`== Розділ 22. Переклад назви розділу`)
. Розділ розбивається на частини, приблизно 8000-10000 символів. Наприклад, у 22му розділі 57080 символів, відповідно
його варто розбити на 6-7 частин і перша частина буде до абзацу 4148.
. Коли частина розділу перекладена, створюється PR (для першої частини -- до master, для наступних -- до попередньої частини)
. На базі цієї гілки створюється нова гілка для наступної частини: `git checkout -b ch22_2_translation`
. Коментарі до PR виправляються у відповідних гілках частин

.Asciidoctor

Усі файли в доволі простому текстовому форматі asciidoc. Ми з нього використовуємо небагато:

. Пам'ятайте, абзаци розділяються порожнім рядком. Новий рядок не означає новий абзац.
. Щоб поставити лапки треба писати так: `\"`У лапках`"`
. Щоб поставити тире треба писати два дефіси.
